### PR TITLE
Fixes for Suggest

### PR DESCRIPTION
**Pull request by gordonbanderson**
Fixes for #6 , and minor additional information

### CODE REVIEW

**Comment by adriannuta** [comment]
Thanks for the PR, but I fixed at e1cbcdb3437ff7e9cd508e2ec27b121b247188a3  in different way to make in line with other calls. Suggest wasn't supposed to receive the $params array and in setBody it needs to call it's parent  as the command is emulated via `/sql`.

**Comment by gordonbanderson** [comment]
I am not yet familiar with the code base and it was after midnight my time - as such, thanks for the fix.

**Comment by adriannuta** [comment]
No problem, thanks for reporting the issue.

**Comment by manticoresearch** [comment]
Offtopic:
@gordonbanderson thanks for your contribution into the client. Just want to let you know that we have public Slack at https://slack.manticoresearch.com/ and I've just created channel `#php` devoted to the new client. That might be useful to discuss some ideas etc.

**Pull request closed without merging**
