### PR TITLE
Fix compatibility of ResultSet with php 8.1+

### PR DESCRIPTION
**Pull request by donhardman**

### CODE REVIEW

**Comment by sanikolaev** [comment]
Hi @donhardman 

I've added yaml for github actions (we were previously using travis ci). Can you please add php 8.1 to the matrix (https://github.com/manticoresoftware/manticoresearch-php/blob/master/.github/workflows/ci.yml#L17) and make sure your change passes the tests in the new version?

**Comment by Fot0n** [comment]
@sanikolaev Одобрите, пожалуйста. Нехорошо, что в логи постоянно валятся предупреждения.

**Comment by sanikolaev** [comment]
> @sanikolaev Одобрите, пожалуйста. Нехорошо, что в логи постоянно валятся предупреждения.

@Fot0n asked to approve the PR. The problem is that we are waiting for a little improvement in the tests, but we can do it ourselves. Thanks for pushing this @Fot0n!

**Comment by Nick-S-2018** [comment]
Done in https://github.com/manticoresoftware/manticoresearch-php/pull/97

**Pull request closed without merging**
